### ISSUE TITLE
knife-solo_data_bag without knife-solo

### ISSUE THREAD

**Issue by allaire** [thbishop/knife-solo_data_bag#17]
The gem is a dep to knife-solo, it does not works without it, giving the error: `ERROR: TypeError: no implicit conversion of Array into String`.

Maybe we should add the dependency to the gemspec or make knife-solo_data_bag works without it?

**Comment by pfink** [comment]
@allaire Can you may tell how you got it to work? I'm facing exactly the same problem right now...

**Comment by flatrocks** [comment]
I cannot speak for anyone else but I had this problem because, since I was creating an encrypted data bag item for testing with kitchen, I did not have access to the default data_bag location.  

Using the
  ```--data-bag-path '.'```
option, the TypeError disappeared and I was able to create a data_bag_item in the current directory.
